server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/users
#      host: user-api
#      port: 27017
#      database: user_db

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring:application:name}
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

